apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base-application/ui
configMapGenerator:
  - name: ui
    namespace: ui
    env: config.properties
    behavior: replace
    options:
      disableNameSuffixHash: true
